server:
  forward-headers-strategy: native
  servlet:
    context-path: /shape
proxy:
  title: ShinyProxy
  port: 8080
  container-wait-time: 90000
  template-path: /srv/external/shiny-proxy/templates/modified_navbar
  landing-page: /app/cif
  docker:
    internal-networking: true
  specs:
  - id: cif
    display-name: Cancer InFocus
    description: Shiny CIF Application
    container-cmd: ["R", "-e", "shiny::runApp('/srv/external/ShinyCIF/app.R')"]
    container-image: cif
    container-volumes: ["/srv/external/:/srv/external/"]
    container-network: external-net
  - id: profiles
    display-name: Cancer InFocus Profiles
    description: Shiny CIF Profiles Application
    container-cmd: ["R", "-e", "shiny::runApp('/srv/external/ShinyCIFProfiles/app.R')"]
    container-image: profiles
    container-volumes: ["/srv/external/:/srv/external/"]
    container-network: external-net
  - id: bivariate
    display-name: Cancer InFocus Bivariate
    description: Shiny CIF Bivariate Application
    container-cmd: ["R", "-e", "shiny::runApp('/srv/external/ShinyCIFBivar/app.R')"]
    container-image: bivar
    container-volumes: ["/srv/external/:/srv/external/"]
    container-network: external-net
logging:
  file:
    name: external.log